
victory_condition: 10

res_names: ['wood', 'brick', 'sheep', 'ore', 'wheat']

victory_points:
  road: 0
  settlement: 1
  city: 2

  longest_road: 2

  largest_army: 2

reqs:
  longest_road: 5
  largest_army: 3

num_res: 19

building_costs:
  road:
    wood: 1
    brick: 1
  settlement:
    wood: 1
    brick: 1
    sheep: 1
    wheat: 1
  city:
    ore: 3
    wheat: 2
  dev_card:
    ore: 1
    sheep: 1
    wheat: 1

building_limits:
  road: 15
  settlement: 5
  city: 4


